### ISSUE TITLE
howto link does not work

### ISSUE THREAD

**Issue by maxlibin** [bambuser/react-native-bambuser-broadcaster#1]
Go to https://bambuser.com/docs/broadcasting/howto/ does not work, can you give a simple guide.

**Comment by peterlofquist** [comment]
Ah that link seems to be out of date, sorry about the inconvenience! You can find the guides to get started with our broadcasting SDKs here: [Android](https://bambuser.com/docs/broadcasting/android/), iOS([Swift 3](https://bambuser.com/docs/broadcasting/ios-swift/), [ObjC](https://bambuser.com/docs/broadcasting/ios-objc/)).

I'll be sure to update the links in our README next time im at the office.
