### ISSUE TITLE
Cannot build project in Xcode 10

### ISSUE THREAD

**Issue by dineshmatta** [bambuser/react-native-bambuser-broadcaster#10]
I started the project from scratch in react-native and after following all steps for ios, I am getting the following errors in Xcode

`Could not build module 'UIKit'`

![image](https://user-images.githubusercontent.com/1083007/63477630-f730a200-c453-11e9-8e37-0a57ef3e85db.png)

**Comment by peterlofquist** [comment]
Thank you for the patience. We've now updated our React Native component to play nicely along with React Native 0.60+. Please follow the updated README.md for this project, it'll point you in the correct direction.

Please open again if you still have issues.
