### ISSUE TITLE
Warning -  Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.

### ISSUE THREAD

**Issue by dineshmatta** [bambuser/react-native-bambuser-broadcaster#11]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: react-native-bambuser-broadcaster, react-native-bambuser-player

Perhaps maintainers of this lib need to update these libraries

**Comment by peterlofquist** [comment]
Thank you for raising this issue, we'll silence this warning in an upcoming release.
