### ISSUE TITLE
onPictureSaved triggered when saving local video instead of onLocalCopySaved in Android

### ISSUE THREAD

**Issue by Vietvantue** [bambuser/react-native-bambuser-broadcaster#12]
When I set **localCopy** to **true** and declare **onLocalCopySaved**, it is never triggered. Instead, **onPictureSaved** was triggered with filePath is local video's file path.

From your source code I got this:

- Register Broadcast

```
if (filename != null) {
  mBroadcaster.storeLocalMedia(filename, mLocalMediaObserver);
}
```

- Send event to JS:

```
private Broadcaster.LocalMediaObserver mLocalMediaObserver = new Broadcaster.LocalMediaObserver() {
      @Override
      public void onLocalMediaClosed(String filePath) {
          WritableMap event = new WritableNativeMap();
          event.putString("filePath", filePath);
          sendEvent(event, "onPictureSaved");
      }
      @Override
      public void onLocalMediaError() {
          WritableMap event = new WritableNativeMap();
          event.putString("message", "Failed to store local media");
          sendEvent(event, "onBroadcastError");
      }
  };
```

**Comment by peterlofquist** [comment]
Thank you for raising this issue! You are very well correct that the wrong callback is called from the LocalMediaObserver.

I'll fix this asap.

**Comment by peterlofquist** [comment]
I fixed the issue here: https://github.com/bambuser/react-native-bambuser-broadcaster/commit/9ec2483f2e9f710c68d896af1546d2a6c6de7b48

Please reopen issue if you still experience this problem. :-)
