### ISSUE TITLE
Invariant Violation "BambuserPlayerView" was not found in the UIManager

### ISSUE THREAD

**Issue by emvigotech** [bambuser/react-native-bambuser-broadcaster#13]
Platform: iOS
React Native: 0.58.6,
Xcode: 10.1
react-native-bambuser-broadcaster: 0.0.8,
react-native-bambuser-player: 0.0.12,

Hi

I have integrated as per the doc https://bambuser.com/docs/broadcasting/ios-objc/ 
I had linked react-native-bambuser-broadcaster manually also manually integrated iOS Broadcast SDK manually without using cocoapod.(Install dependencies manually)

I am able to broadcast live video myself but not able to view others live streaming video.

![IMG_0366](https://user-images.githubusercontent.com/26790656/64013001-8288f200-cb3c-11e9-882d-0addcd2e7ca6.PNG)

**Comment by peterlofquist** [comment]
We currently only support the latest React Native version, if you wish to use an older version of React Native, in your case `0.58.6` I'd suggest you do the following:

1) Install libbambuser via Cocoapods (or manually, it should work the same way, you might have to change some libbambuser import line after step 4, Xcode will tell you more about it).
2) Run `yarn add react-native-bambuser-player`.
3) Run `react-native link react-native-bambuser-player` (This doesn't do anything of value for your iOS setup in this case, but it should link the files properly for the Android part of your project).
4) Navigate to `[your-project]/node_modules/react-native-bambuser-player/ios`, drag and drop the `*.h/.m` files from named directory into your React Native Xcode project. Check the box `Copy items if needed` and accept.

Your Xcode project should now look something like this:
<img width="264" alt="Screenshot 2019-09-02 at 09 42 02" src="https://user-images.githubusercontent.com/2319341/64098225-9adc5500-cd66-11e9-932a-a997a7b4d191.png">

After these steps the React Native UIManager should be able to find all the files it needs to run properly.

Please note that by using `react-native-bambuser-player` this way you have to manually update this projects iOS files in the future.

**Comment by emvigotech** [comment]
Thanks it worked
