### ISSUE TITLE
After using zoom property getting error

### ISSUE THREAD

**Issue by dineshmatta** [bambuser/react-native-bambuser-broadcaster#14]
Hi,

Getting below error when using zoom property on **RNBambuserBroadcaster** component

![Screenshot_20190916-232134](https://user-images.githubusercontent.com/1083007/65009747-cf5e1e00-d8db-11e9-8216-a7b38b9be420.jpg)

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

Can you please look at the above issue, as this feature is really important for us before we release our app

**Comment by peterlofquist** [comment]
Should be fixed here: 3a08fca49b5491e2a649d70fa887fef21597dde3

Please reopen issue if issue still exists after updating the component to `0.0.11`. Happy coding!

**Comment by dineshmatta** [comment]
Hey @peterlofquist 

I tested the zoom prop with all the possible values between 0 and 1 and it looks like zoom feature doesn't work on all the values, for example, if I add a slider in my react native app which emits the values like 0.1, 0.3, 0.4, 0.5078125, 0.5390625,  0.6640625, so after it works for some initial value and at some points it doesn't matter which value I choose for zoom it doesn't work because it looks like it has already zoomed in completely.

Can you please confirm if zoom feature works uniform across all values?

**Comment by dineshmatta** [comment]
Hi @peterlofquist 

Did you get the chance to look at the above issue, as it stopping us from using the slider in our camera view
