### ISSUE TITLE
zoom prop doesn't work for all the values between 0 and 1

### ISSUE THREAD

**Issue by dineshmatta** [bambuser/react-native-bambuser-broadcaster#17]
Hey @peterlofquist

I tested the zoom prop with all the possible values between 0 and 1 and it looks like zoom feature doesn't work on all the values, for example, if I add a slider in my react native app which emits the values(between 0 and 1) like 0.1, 0.3, 0.4, 0.5078125, 0.5390625, 0.6640625, so after it works for some initial value and at some points it doesn't matter which value I choose for zoom it doesn't work because it looks like it has already zoomed in completely.

Can you please confirm if zoom feature works uniform across all values?

**Comment by peterlofquist** [comment]
Sorry for getting back to this issue with some slight delay. I have not been able to reproduce this issue on either iOS or Android. Could you point me towards some steps to reproduce this issue?

The code I've verified that works with the latest version of react-native(0.61.4) and react-native-bambuser-broadcaster(0.0.11).

```
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, {Fragment, Component} from 'react';
import {
  View,
  SafeAreaView,
  Slider,
} from 'react-native';

import RNBambuserBroadcaster from 'react-native-bambuser-broadcaster';

class App extends Component {
  
  constructor(props) {
    super(props);
    this.state = {
      zoom: 0,
    };
  }

  render() {
    return (
      <Fragment>
        <SafeAreaView style={{
          flex: 1,
        }}>
          <RNBambuserBroadcaster style={{
            flex: 1,
          }}
          zoom={this.state.zoom}
          ref={ref => this.player = ref}
          applicationId='YOUR-APP-ID'/>
          <View style={{
            position: 'absolute',
            width: '100%',
            height: '100%',
            padding: 20
          }}>
            <Slider value={0} onValueChange={value => {
              console.log('Setting zoom value:', value);
              this.setState({ zoom: value });
            }} />
          </View>
        </SafeAreaView>
      </Fragment>
    );
  }
}

export default App;
```

**Comment by peterlofquist** [comment]
Closing - please open if this issue still persists
