### ISSUE TITLE
[Android] Crash on Android setZoom() and AudioCapturer

### ISSUE THREAD

**Issue by nttung291** [bambuser/react-native-bambuser-broadcaster#22]
I got the crashes on fabric and dont know how to investigate it. May be it casued by bambuser sdk. I use react-native-bambuser and found no proplem in JS .

It looks like the onCameraPreviewStateChanged callback in that component will call setZoom() without condition - even when the camera is going away (and setZoom() should not be called). Looks like it's a race condition that might trigger that crash.

The other crash is caused by AudioCapturer

Are there any idea to resolve it? 

<img width="1530" alt="Screen Shot 2020-02-03 at 5 13 53 PM" src="https://user-images.githubusercontent.com/29893869/73927939-e04c1200-4904-11ea-9dc5-43fa3cf9d2ee.png">
<img width="1518" alt="Screen Shot 2020-02-03 at 6 09 36 PM" src="https://user-images.githubusercontent.com/29893869/73927944-e3df9900-4904-11ea-83d7-1fff92db783c.png">

**Comment by peterlofquist** [comment]
Thanks for the issue report!

We just released a new version of the react-native-bambuser-broadcaster (0.0.13) which should fix the issue with the potential race condition which could occur.

We're still working on the second issue in this issue report. I'll get back to you when I know more!
