### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by felippepuhle** [bambuser/react-native-bambuser-broadcaster#24]
Is there a way we can add auto start broadcasting?

I'm trying to implement mysel, but sometimes I get `onStartBroadcastNotReady`.

Thanks!

**Comment by peterlofquist** [comment]
Yes you can implement this yourself by using the `onCameraReady` + `onStartBroadcastNotReady` callbacks.

When you first receive the `onCameraReady` event you can call the `this.myBroadcasterRef.startBroadcast();`. If you get the `onStartBroadcastNotReady` you set a small timeout and then retry again with the `.startBroadcast()`. You'll have to build your own logic to gradually back off and make a decision on how many retries you allow. If something is wrong you should be getting an error via the `onBroadcastError` callback.

I hope this helps

**Comment by felippepuhle** [comment]
@peterlofquist already doing this `auto-retry`, but it's not the perfect solution IMO. I was wondering if there's a way we can receive a `broadcast ready` event in the future (it's not urgent, BTW).

Thanks!

**Comment by peterlofquist** [comment]
I'll take note of this feature request and we'll see what we can do. :-)
