### ISSUE TITLE
'libbambuser.h' file not found

### ISSUE THREAD

**Issue by ankitgauravapporio** [bambuser/react-native-bambuser-broadcaster#26]
Hi all , i am using react native  version 0.59.0 , due to my other dependencies, can anyone please guide me how to integrate and 'libbambuser.h' file not found  will be removed, thank you

**Comment by peterlofquist** [comment]
Thanks for your issue report!

Please refer to this documentation to use this component in react native version 0.59.0: https://github.com/bambuser/react-native-bambuser-broadcaster/blob/4d0cac0f55bfce156be7ecda55d69f251d824c4c/README.md

**Comment by ankitgauravapporio** [comment]
hello Peter , thank you for your support

cheers

**Comment by ankitgauravapporio** [comment]
@peterlofquist can you please provide any example documentation , thanks in advance

**Comment by peterlofquist** [comment]
It is fully documented in the link I mentioned above. Underneath here is a quick list but please refer to full documentation for any more details.

1. Add react-native-bambuser-broadcaster to your React Native project.
`$ yarn add react-native-bambuser-broadcaster@0.0.8 --save`

2. Download iOS & Android SDKs from https://dashboard.bambuser.com/developer

3.1 Android only: Head over to https://bambuser.com/docs/broadcasting/android/ and follow the Android sections Add the broadcast SDK and Add required Android app permissions and features for the Android project within your React Native project. Important note: when adding the libbambuser subproject, make sure you name it libbambuser, the React Native component will look for this subproject when building your React Native app.

3.2 iOS only: Go to https://bambuser.com/docs/broadcasting/ios-objc/ and follow the iOS sections Install dependencies manually, Add the broadcast SDK and Enable camera and microphone access for the iOS project within your React Native project.

4. run `$ react-native link react-native-bambuser-broadcaster`

**Comment by ankitgauravapporio** [comment]
Hi @peterlofquist , the issue still exist in .059.2 after doing all the integration , #18 is for higher version , so can you help me for lower versions

**Comment by ithustle** [comment]
Same here on RN 0.62.2
