### ISSUE TITLE
Are separate android and ios applicationIds required?

### ISSUE THREAD

**Issue by snobear** [bambuser/react-native-bambuser-broadcaster#28]
When creating an application Id, which one should be used for React Native? 

![image](https://user-images.githubusercontent.com/696230/78175978-c07b2b00-7429-11ea-99c7-92329f5fd3ee.png)

Is it required to use iOS for iOS, and Android for Android? Or will one of these selections work for both?

Also, I realize this should be fetched from the backend, which I'll implement later, but just want to confirm what is required. Thanks!

**Comment by karanpratapsingh** [comment]
yes, both are required

**Comment by snobear** [comment]
OK thanks @karanpratapsingh for confirming.
