### ISSUE TITLE
Can you provide an example ?

### ISSUE THREAD

**Issue by baotoan1905** [bambuser/react-native-bambuser-broadcaster#29]
I followed the instruction for react-native 0.60.0 but when tried it out in android, nothing doesn't seem to work, no error, no event callback
import RNBambuserBroadcaster from 'react-native-bambuser-broadcaster';

<RNBambuserBroadcaster
        applicationId={applicationId}
        ref={ref => {
          myBroadcasterRef = ref;
        }}
        onBroadcastStarted={handleOnBroadcastStarted}
        onBroadcastIdReceived={handleOnBroadcastIdReceived}
        onBroadcastError={handleOnBroadcastError}
      />

Then I call myBroadcasterRef.startBroadcast();

**Comment by peacepostman** [comment]
Hello, same problem here, all seems to be well imported but nothing happens, i'm also requesting permissions for camera and audio but like @baotoan1905 , nothing is happening :/

**Comment by baotoan1905** [comment]
@peacepostman I was able to make it work by add property style={{ width: 200, height: 200 }}, You can change width and height with your value.
Hope it can helps.

**Comment by peacepostman** [comment]
Okay, thanks for your feedback, i will have a look, did you try on ios too ?

**Comment by baotoan1905** [comment]
> Okay, thanks for your feedback, i will have a look, did you try on ios too ?

I haven't tried it yet. Will try later.

**Comment by peacepostman** [comment]
It's fully working on android, thanks mate

**Comment by bfarrgaynor** [comment]
Hey guys, what was the issue here? Was it the permissions afterall?

**Comment by baotoan1905** [comment]
Hi @bfarrgaynor Yes, we missed the configuration in android for permission.
@peacepostman It now works great in both android and ios.

**Comment by peterlofquist** [comment]
Closing issue
