### ISSUE TITLE
Invariant Violation:

### ISSUE THREAD

**Issue by CyrusZei** [bambuser/react-native-bambuser-broadcaster#3]
Invariant Violation: requireNativeComponent: "BambuserBroadcasterView" was not found in the UIManager.

This error is located at:
    in BambuserBroadcasterView (at react-native-bambuser-broadcaster/index.js:235)
    in RNBambuserBroadcaster (at MainScreen.js:48)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at MainScreen.js:45)
    in MainScreen (at Main.js:149)
    in Route (at Main.js:146)
    in Switch (at Main.js:112)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at Main.js:108)
    in Provider (at Main.js:105)
    in Main (at App.js:261)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at App.js:260)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at App.js:259)
    in Route (at App.js:255)
    in PrivateRoute (at App.js:291)
    in Switch (at App.js:279)
    in RCTView (at View.js:45)
    in View (created by Context.Consumer)
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at App.js:278)
    in Router (created by MemoryRouter)
    in MemoryRouter (at NativeRouter.js:10)
    in NativeRouter (at App.js:277)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)

getNativeComponentAttributes
    getNativeComponentAttributes.js:28:2
<unknown>
    requireNativeComponent.js:26:4
Object.exports.get
    ReactNativeViewConfigRegistry.js:104:17
createInstance
    ReactNativeRenderer-dev.js:3946:49
completeWork
    ReactNativeRenderer-dev.js:13385:25
completeUnitOfWork
    ReactNativeRenderer-dev.js:15892:25
performUnitOfWork
    ReactNativeRenderer-dev.js:16103:11
workLoop
    ReactNativeRenderer-dev.js:16115:23
renderRoot
    ReactNativeRenderer-dev.js:16219:6

Can you guys please help me with this. Have been fighting with this for 3 days now and I soon don't have any hair left on my head.

I did follow your guide to add this to the ios, but still, it does not work.

**Comment by CyrusZei** [comment]
Has this been tested with react 0.58.rc2 ?

**Comment by jhltom** [comment]
I'm getting the same error. Is there a solution for this?

**Comment by jhltom** [comment]
After install the dependencies and broadcast SDK, and enabling camera and microphone access I get this error on Xcode `linker command failed with exit code 1 (use -v to see invocation)`. Would this be related to the above error I'm getting?

**Comment by peterlofquist** [comment]
I can reproduce this error mentioned above if I bypass the step to run the command `$ react-native link react-native-bambuser-broadcaster` after including the SDK and adding the yarn package `react-native-bambuser-broadcaster`.

After I run the command above it works as intended (just tested with react-native version 0.59.5). If you've already tried the above command and it still doesn't work please describe the steps to reproduce the error mentioned above and I'll dig further into this issue.

**Comment by jhltom** [comment]
I fixed the problem, thanks! When adding the broadcast sdk I had renamed the `prebuild/`directory to `lbambuser` and was getting this error on xcode. 

![Screen Shot 2019-04-30 at 1 29 27 AM](https://user-images.githubusercontent.com/43786249/56911496-01ffa980-6ae8-11e9-9e1c-0f1dfdfd6758.png)

So I changed the directory back to `prebuild`, then re-installed and linked `react-native-bambuser-broadcaster`and now I can finally run my react-native project on my device without getting the above error.

**Comment by peterlofquist** [comment]
@jhltom thanks for that information!

What seems to be happening here is that when you first include the SDK in your Xcode project your projects build settings add `$(PROJECT_DIR)/prebuilt/lib` to the `Library Search Paths` list. When you later change the `prebuilt` group name to `lbambuser` the `Library Search Paths` list is not updated with this new group name, hence the linker command fails when building the project.

The solution for now would be to update the `Library Search Paths` entry in Build Settings with the new name of the prebuilt-group after renaming it.
