### ISSUE TITLE
Does this project require react-native link?

### ISSUE THREAD

**Issue by bfarrgaynor** [bambuser/react-native-bambuser-broadcaster#30]
It seems as though you might be missing a 'react-native link' in the instructions here: https://github.com/bambuser/react-native-bambuser-broadcaster#to-automatically-link-this-react-native-module-to-your-xcodeandroid-projects-run-the-following-command

**Comment by peterlofquist** [comment]
If you are using RN version 0.60 or under you should use the version 0.0.8 of this repository. The README for that version has the link command documented.

https://github.com/bambuser/react-native-bambuser-broadcaster/blob/4d0cac0f55bfce156be7ecda55d69f251d824c4c/README.md#to-automatically-link-this-react-native-module-to-your-xcodeandroid-projects-run-the-following-command

Additional info
https://reactnative.dev/blog/2019/07/03/version-60#native-modules-are-now-autolinked

**Comment by bfarrgaynor** [comment]
Thanks @peterlofquist. I was able to get it going!
