### ISSUE TITLE
Populating the "tags" field and "customData" prop type

### ISSUE THREAD

**Issue by jhltom** [bambuser/react-native-bambuser-broadcaster#4]
Is there a prop to populate the "tags" field in the broadcast's metadata? 

Also, when I try to populate `customData: Object` with an associative array such as `{"chat":"zxv", "tag":"travel"}` I get a warning saying `customData` is expecting a `string` not and an `object`

**Comment by peterlofquist** [comment]
Thanks for the report!

I've pushed an update to NPM with version `0.0.8` of this repository, that version should have this issue fixed so it works on both Android and iOS. 

Simply use `<RNBambuserBroadcaster customData={{ tags: 'foo', bar: 'beer' }} />` to attach your own custom data. 🙂

**Comment by jhltom** [comment]
Given a `const customData` that successfully stores the `customData` metadata from a broadcast, `console.log(customData)` indeed prints `"{"foo":"bar", "bar":"beer"}"`  but `console.log(customData.foo)` prints `undefined`.  

How can I access the data in `customData`? It looks like `customData` is returning a string not an object..!

**Comment by peterlofquist** [comment]
@jhltom glad you found your way to use `JSON.parse()`, that function together with JSON.stringify() comes in very handy when transforming JSON objects to strings and vice versa! 🙂

Always happy to help, happy coding!

**Comment by felippepuhle** [comment]
@peterlofquist I think there's some misbehavior on this approach.

I want to populate 'tags' metadata, I don't want to add a new 'tags' field on customData.

Is that possible? Can we reopen this issue?

Thanks!

**Comment by peterlofquist** [comment]
@felippepuhle take a look here: https://bambuser.com/docs/broadcasting/features/#using-hashtags

If you want to populate the 'tags' metadata you provide that in the title field as `#myTag` for the broadcaster component.

**Comment by felippepuhle** [comment]
@peterlofquist that's awesome, didn't notice it. thanks!
