### ISSUE TITLE
Updating customData field

### ISSUE THREAD

**Issue by jhltom** [bambuser/react-native-bambuser-broadcaster#5]
Is it possible to update the customData field after a broadcast has been created? For instance if we would to keep a count for likes in customData, would it be possible to update this with a http request?

**Comment by peterlofquist** [comment]
No, it is not possible to update the customData after a broadcast have been started. I'd suggest you store this kind of metadata in some other data storage(database etc).

**Comment by jhltom** [comment]
Thank you for your response!
