### ISSUE TITLE
Mute microphone

### ISSUE THREAD

**Issue by seung1231** [bambuser/react-native-bambuser-broadcaster#6]
What would be the best way to mute broadcaster's microphone using bambuser API?

**Comment by peterlofquist** [comment]
If you do not wish to record any audio for your broadcast you can turn this off by setting the component prop `audioQuality`, available values for this property is `RNBambuserBroadcaster.AUDIO_QUALITY.HIGH || RNBambuserBroadcaster.AUDIO_QUALITY.LOW || RNBambuserBroadcaster.AUDIO_QUALITY.MUTE`. Please beware that this property has a bit different behaviour iOS and Android, so be sure to read the documentation found below before making your decision to mute while a broadcast is currently ongoing.

Reference documentation iOS: https://bambuser.com/docs/reference/ios-sdk-current/interface_bambuser_view.html#ae511589dad6b40bc5d76bb7cfbf34d68
Reference documentation Android: https://bambuser.com/docs/reference/android-sdk-current/

**Comment by jhltom** [comment]
Is there a way to mute an on going broadcast? The audioQuality prop allows users to start a broadcast mute but I was wondering if there is a way to turn on/off the mute feature while live streaming.

**Comment by peterlofquist** [comment]
Sorry for the late reply. As of right now you can not mute a ongoing live stream.
