### ISSUE TITLE
Tried to Register twoviews

### ISSUE THREAD

**Issue by balu3083** [bambuser/react-native-bambuser-broadcaster#7]
Hi ,
Hi I am getting an error like "Tried to register two views with the same name  BambuserBroadcastView" help me to resolve this issue

Thanks
Balakrishnan

**Comment by Vietvantue** [comment]
I think you should describe issue more details. With step to reproduce and screenshot.

**Comment by peterlofquist** [comment]
Please provide some more information regarding this issue. When is it happening, what are you trying to accomplish? If possible, provide some pseudo code which would potentially make it easier for me to debug myself.

**Comment by balu3083** [comment]
Hi,
I have followed below steps to integrate  this sdk
1) I download the android sdk from the dashboard
2) I added the sdk in my project and added the path in settings.gradle file  (Inside the android platform)
include ':libbambuser'
project(':libbambuser').projectDir = new File('/libbambuser-0.9.17')
3)  I just link the module using below comment 
" react-native link react-native-bambuser-broadcaster"
4)  After that I tried to call the below tag with my applicationId  but it showing white blank screen (nothing happend ) 
<RNBambuserBroadcaster applicationId={yourApplicationId} />

**Comment by balu3083** [comment]
<RNBambuserBroadcaster applicationId={yourApplicationId} />

**Comment by balu3083** [comment]
RNBambuserBroadcaster applicationId={yourApplicationId}

**Comment by Vietvantue** [comment]
> RNBambuserBroadcaster applicationId={yourApplicationId}

I think you should set style to your RNBambuserBroadcaster.
style={{ flex: 1}}

**Comment by balu3083** [comment]
tried the above style not working

**Comment by Vietvantue** [comment]
> tried the above style not working

Let try it: https://labs.bambuser.com/mg/App.js

**Comment by balu3083** [comment]
Hi ,

When I try the above code I am getting black rectangle at right corner 
![Screenshot_20190703-115813](https://user-images.githubusercontent.com/45266052/60569191-5810f780-9d8c-11e9-80b2-47a16748d7c1.png)

Also I have tried the samecode  with broadcaster this is also giving the same result screen  no camera has opened  please find my broadcast code from below link

https://drive.google.com/file/d/1FY3q9YsSYcFtUXPPuj-1pq9TZwjxK-pQ/view?usp=sharing

Thanks
Balakrishnan

**Comment by balu3083** [comment]
Hi,
Camera is enabled now . It was a camera permission issue but I couldn't see the broadcasting video on bambuser player(https://dist.bambuser.net/player/)   aswell as my app player  please check my streamer 
code and let me know what else I need to add
https://drive.google.com/file/d/1FY3q9YsSYcFtUXPPuj-1pq9TZwjxK-pQ/view?usp=sharing

Thanks
Balakrishnan

**Comment by balu3083** [comment]
Hi,
Now it is working :) I just called startBroadcast method after 5 seconds delay. Thank you so much for your help
Thanks
Balakrishnan
