### ISSUE TITLE
Execution failed for task ':app:installDebug'.

### ISSUE THREAD

**Issue by amdrade** [bambuser/react-native-bambuser-broadcaster#8]
Erro on run ` react-native run-android`

Use:
react: 16.8.6,
react-native: 0.60.3,
react-native-bambuser-broadcaster: ^0.0.8

**Comment by rstcom919** [comment]
"react": "16.8.3",
 "react-native": "0.59.8",
 "react-native-bambuser-broadcaster": "0.0.8",

Please use these versions: it is working well on my side

**Comment by peterlofquist** [comment]
Reopen if issue persists.
